name: Full integration workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    
jobs:
  build:
    runs-on: ubuntu-latest
    #needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: build/
      
  release:
      needs: build
      runs-on: ubuntu-latest
      permissions:
        issues: write
        contents: write
        pull-requests: write
        
      steps:
        - name: Release
          uses: googleapis/release-please-action@v4
          with:
            # this assumes that you have created a personal access token
            # (PAT) and configured it as a GitHub action secret named
            token: ${{ secrets.GITHUB_TOKEN }}
            # this is a built-in strategy in release-please, see "Action Inputs"
            # for more options
            release-type: simple
  
  #test:
  #  runs-on: ubuntu-latest
  #  
  #  steps:
  #  - uses: actions/checkout@v4
  #  
  #  - name: Setup Node.js
  #    uses: actions/setup-node@v4
  #    with:
  #      node-version: 20.x
  #      cache: 'npm'
  #  
  #  - name: Install dependencies
  #    run: npm ci
  #  
  #  - name: Run tests
  #    run: npm test -- --coverage --watchAll=false
  #  
  #  - name: Upload coverage reports
  #    uses: codecov/codecov-action@v3
  #    with:
  #      file: ./coverage/lcov.info
